---
title: "RStudio Shortcuts 1"
author: "佐藤 健治"
date: '2017-04-17'
output:
  xaringan::moon_reader:
    css: ../asset/remark-css/style.css
    lib_dir: libs
    nature:
      countIncrementalSlides: no
      highlightLines: yes
      highlightStyle: github
subtitle: 経済動学 (2017Q1)
---


```{r setup, include=FALSE}
source("../R/utils.R")
knitr::opts_chunk$set(
  fig.align = "center",
  out.height = "380px",
  dpi = 180
)
```

## Keyboard Shortcuts

Coding involves very exciting repetition.

- Write code
- Test how it works
- Repeat until you have a desired result.

Moving your hand back and forth between the keyboard and mouse slows down your brain activity.

Learn some of RStudio shortcuts and accelerate your work!

---

## The most important of all

You can reference all the keyboard shortcuts of RStudio by pressing **Alt/Option+Shift+K**

Take a couple of minutes everyday to learn one or two shortcuts.


| Description             | Win & Linux  | Mac             |
|:------------------------|:-------------|:----------------|
| Show Keyboard Shortcuts | Alt+Shift+K  | Option+Shift+K  |


---

## What to learn first

| Description                  | Win & Linux  | Mac              |
|:-----------------------------|:-------------|:-----------------|
| New document                 | Ctrl+Shift+N | Command+Shift+N  |
| Move focus to Source Editor  | Ctrl+1       | Ctrl+1           |
| Move focus to Console	       | Ctrl+2	      | Ctrl+2           |
| Source the current document	 | Ctrl+Shift+S	| Command+Shift+S  |
| Insert code section          | Ctrl+Shift+R | Command+Shift+R  |
| Run the current code section | Ctrl+Alt+T   | Command+Option+T |
		
