---
title: ガイダンス資料
subtitle: 経済動学 (2017Q1)
author: "佐藤 健治"
date: "2017-04-10"
output:
  beamer_presentation:
    template: null
    includes:
      in_header:
        - ../asset/styles/luatexja.sty
        - ../asset/styles/beamer.sty
    latex_engine: lualatex
  slidy_presentation: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Mechanics

## 講義概要

- 担当教員
    - 佐藤健治 Kenji Sato
    - Email: mail@kenjisato.jp
    - GitHub: kenjisato
- 時間・教室
    - 月曜 4限 (15:10 -- 16:40) @I332
    - 木曜 4限 (15:10 -- 16:40) @I332
- 講義計画
    - 講義 15回
    - 期末試験なし

## テーマと目標

この講義では，経済動学システム，特に線形動学システムの基礎的な性質を学びます。

経済学専攻の学生にとって馴染みの薄い数学を使うことになりますが，練習問題とコンピュータを使った宿題を通して，理解を補強します。真面目に講義を受ければ経済動学システム，特にマクロモデルの動学，に関する深いレベルの理解を得られるでしょう

この講義は，DSGEモデル，マクロ実証，非線形経済動学等の学習に進む上で基礎的な知識と技術を獲得するのに役立ちます。


## FAQ (その1)

- この講義ではどのようなモデルを扱いますか？
    - 線形合理的期待モデルと呼ばれるクラスのモデルを扱います。
      ただし，具体的な経済現象を説明するためにそのようなモデルを使いません。
      多くのモデルに共通する一般構造のみを仮定して数値手法の理論と実装を学びます。
- Dynareを使えばマクロモデルのシミュレーションはできるのだから，
  基礎を詳しく知る必要はないのでは？
    - 研究というのは誰かが作った道具を使う以上のことが要求されるもの
      ではないでしょうか。深く学びましょう。
      
## FAQ (その2)

- ほとんどの経済モデルは非線形なので，線形より非線形を学びたいのですが？
    - 線形モデルが分からないまま非線形が理解できるというのは考えにくいです。
      何故かと言うと，非線形モデルの主な分析ツールは関数解析学であり，
      それは無限次元の線形空間上の写像に関する性質を調べる学問だからです。
      有限次元の線形空間を舞台にした線形モデルをきちんと理解していないと，
      非線形モデルの理解は難しいのです。


## 講義ノート（lecture notes）

講義は講義ノートに沿って進めます https://kenjisato.github.io/led/  
特定の教科書を購入する必要はありません。

この講義ノートは完成品（仮にそういうものがあればという話ですが）ではないので，
コメントを歓迎します。後で述べるように，講義ノートへのコメントは評価の対象になります。


## 評価（assessment）

- 宿題と授業への積極的な参加を評価します。
- 宿題
    - 10〜15回
    - 講義で扱う内容を簡略化したもので，1〜2時間で解けるはずのものを出題
    - 短いレポートおよびコーディング問題
    - すべて R, RStudio, RMarkdown (+ LaTeX) で書いて GitHub 経由で提出する
- 積極的な参加
    - 講義中やチャットルームでの質問や
    - 講義ノートの誤りや記述の不明瞭な点を指摘するなどの建設的なコメントを評価します

## サポート（support）

- Slack チーム
    - https://rokkoecon-slack-invite.herokuapp.com/
    - **GitHub** アカウントと同じアカウント名を設定してください！
    - 学習サポートのための Slack チームを開設しています。
      プライバシーに関わる質問でないかぎりこちらでお願いします。
    - 質問は日本語か英語で
- TA
    - 松井 暉 Akira Matsui
    - GitHub: akira55

数学やコンピュータに自信のない人もぜひ続けて参加してください。
練習問題を通して，一揃いの技術を伝授します。


## Special Supports for International Students

- All assignments will be provided in English (and some of them are 
  translated into Japanese) and you can write solutions in English. 
- You can ask questions in English on Slack.
- I haven't translated my lecture notes into English, but if some of you 
  can help, I will do that.
  

# Computer Skills

## R

すでに述べた通り，この講義では主なプログラミング言語として R を用います。

経済動学のシミュレーションにとって R が特別優れているという訳ではありません。むしろ性能面では望ましくないかもしれません。しかし，R は今や Python と並んで人気のある言語であり，統計分析を専門とする人が大きなコミュニティを形成しているので，今後実証研究を行う可能性がある学生にとって学んで損のない技術でしょう。

この講義では統計分析を行いませんが，それでもなお R が役に立つということをお見せしたいと思います。


## Rmarkdown

この講義では，宿題として簡単な（2ページ程度の）ノートを書いてもらう課題をいくつか出しますが，すべて Rmarkdown という形式で書いていただきます。文書の中に R コードを書けば，その出力が文書中に埋め込まれます。数値計算とレポート作成を一箇所で実行できるので，コピー＆ペーストに起因する更新し忘れの問題を減らすことができます。

Rmarkdown は非常に簡潔な書式で書くことができ，pandoc という外部アプリケーションを通して HTML，MS Word，LaTeX，そして（LaTeX を介して）PDF 形式の文書として出力することができます。この講義で配布する資料，スライドはすべて Rmarkdown 形式で書かれ， pandoc と LaTeX で変換されたものです。

課題を通して，美しい文章・スライドを作る方法を身につけてください。

## Git + GitHub

Git というソースコードの履歴を記録するアプリケーションがあります。大規模な開発を複数人で行うときに非常に役に立つ（らしい）のですが，これは1人あるいは数人で論文を書くときにも役に立ちます。この講義では，GitHub という Git をベースにしたオンラインのソースコード共有サービスを利用して，課題の配布と提出を行います。

GitHub や類似のサービスを通して論文のコードやデータを配布する経済学者も増えていますので，使い方を今のうちに身につけておくと良いでしょう。

GitHub アカウントを持っていない人は必ず作成してください。今後何年間か使い続けるつもりでアカウント名を付けることを推奨します。

## Slack 

学習サポートには Slack を使います。Slack はプログラマの間で人気のあるチャットツールです。メールに比べてコードの共有が容易ですし，質問や回答を受講生全員が見ることができるので，デリケートな質問以外はすべてこちらでお願いします。

登録には https://rokkoecon-slack-invite.herokuapp.com/ から招待リンクを受け取ってください。なお，質問や他の受講生の質問に対する回答を活発に行っている学生にはよい評点を付けますので，**GitHub と同じアカウント名で登録してください**。



